[typescript/graphql-nextjs] update nexus-prisma schema in README
prisma/prisma-examples pull request #2359
Opened 2020-12-16 23:20 UTC by gianpaj

2021-01-02 14:46 UTC, kadirselcuk approved these changes

2021-02-16 11:18 UTC, janpio requested changes
The content of this README comes from a template in the .github folder and should not be edited directly.

2021-02-16 13:47 UTC, jasonkuhrt commented
Hey @gianpaj could you explain what this change is for? Thanks

2021-02-22 16:12 UTC, janpio commented
@nikolasburk just merged an update on that example, which brings the README in line with your changes @gianpaj. Do you agree with that and this PR can be closed?

2021-02-25 20:18 UTC, closed without merging