fix : improvements
prisma/prisma-examples pull request #2364
Opened 2020-12-18 11:42 UTC by Aperrix

- Add fastify-blipp to display availables routes in dev env
- Fix response typo (from res.send to return because req is async)
- Fix server start function

2021-01-13 11:51 UTC, 2color requested changes
Thanks for the PR @Aperrix.

For simplicity, I'd remove the `fastify-blipp` plugin. 

I left a couple of small comments. 

Finally, be sure to run prettier for consistent code style.

2021-01-13 11:51 UTC, 2color commented on javascript/rest-fastify/package.json
> +    "dev": "node src/index.js && npm run studio",
I would avoid launching studio on the dev command for consistency with the other examples.

2021-01-13 11:52 UTC, 2color commented on javascript/rest-fastify/package.json
> +    "fastify-blipp": "^3.0.0",
I'd remove `fastify-blipp` so that the example focuses on the bare minimum to integrate Prisma with Fastify

2021-02-16 11:15 UTC, janpio commented
Can you take another look at this @Aperrix? Thanks.

2022-11-07 11:56 UTC, closed without merging

2022-11-07 11:56 UTC, ruheni commented
Closing this in favor of #4233