New Prisma example - rest-express-auth
prisma/prisma-examples pull request #2869
Opened 2021-05-18 17:59 UTC by eternalmoon1234

This is the PR where I am working on the rest-express-auth example, details [here](https://github.com/prisma/prisma-examples/issues/2838). This is currently a draft.

2021-06-12 16:21 UTC, ruheni commented on typescript/rest-express-auth/package.json
> +  "devDependencies": {
Include `prisma` dev dependency

2021-06-12 16:24 UTC, ruheni commented on typescript/rest-express-auth/.gitignore
> +*.env*
The `prisma-examples` repository includes a `.gitignore` file at the root of the project. This won't be necessary 🙂

2021-06-12 16:31 UTC, ruheni commented on typescript/rest-express-auth/src/routes/Auth.ts
> +      sessionID: '',
I think we can use the `null` value here.

For more information on what setting `null` does, you can refer to this page on our docs: [Null and undefined (Reference)](https://www.prisma.io/docs/concepts/components/prisma-client/null-and-undefined).

2021-11-22 09:48 UTC, ruheni commented
Hi @eternalmoon1234 👋🏽

Do you have any updates on this PR? Would you like any help pushing this across the finish line? 🙂

2022-03-31 15:22 UTC, ruheni commented
Hey @eternalmoon1234 👋🏽

Do you intend to pick up this PR, and do you need any help?

2022-07-16 06:47 UTC, eternalmoon1234 commented
Hey @ruheni, ✋
Yes, I do intend to pick up the PR and will finish it by the end of next week! Sorry for the inactivity with this, I've been coding on and off recently and I must say I forgot about this 😅

Looking forward to finishing this!

2023-03-07 22:01 UTC, eternalmoon1234 commented
Hey @ruheni 👋 

I finally finished up this PR. I've implemented the changes you proposed (as well as some others) and have followed the same standard of the [rest-express-auth](https://github.com/eternalmoon1234/prisma-examples/tree/latest/typescript/rest-express) example. 

Please review & propose any changes when you can!

2023-03-16 12:08 UTC, ruheni requested changes
This looks pretty good. I've left some comments. The example seems to be missing a test for it. You can add one in the `.github/tests` folder.

One other thing I didn't include in the comments is that I think some endpoints might not require authentication, such as `/feed` and `/post/:id` (both GET endpoints). I would recommend protecting endpoints with _write_  operations in general. Let me know if you would like any help determining what endpoints to protect

2023-03-16 12:08 UTC, ruheni commented on .github/readmes/typescript/rest-express-auth/README.md
> +- [Using the GraphQL API](#using-the-rest-api)
REST API here 😅

2023-03-16 12:08 UTC, ruheni commented on .github/readmes/typescript/rest-express-auth/README.md
> +This example shows how to implement a **GraphQL server with TypeScript** with the following stack:
REST API here too.

2023-03-16 12:08 UTC, ruheni commented on .github/readmes/_using-the-rest-api-auth.md
Could you document which endpoints require authentication here? e.g documentation
- `/post`: (protected) ...

Feel free to adjust the wording as you prefer 🙂

2023-03-16 12:08 UTC, ruheni commented on .github/readmes/_using-the-rest-api-auth.md
There seems to be a content mismatch between the generated READMe and this template. Update the relevant questions to prevent the contents of the main README from being overwritten on template generation

2023-03-16 12:08 UTC, ruheni commented on typescript/rest-express-auth/README.md
I would recommend referring to the other templates In the `.github/readmes/typescript` folder to see what the structure is like to avoid content redundancy.

2023-03-16 12:08 UTC, ruheni commented on typescript/rest-express-auth/prisma/seed.ts
> +    password: 'testPassword',
I would recommend the following for the test data in the event a user tries to log in with the test user:
```suggestion
    password: await argon2.hash('testPassword'),
```

2023-03-16 13:16 UTC, janpio commented on .github/readmes/typescript/rest-express-auth/README.md
> +- [Using the GraphQL API](#using-the-rest-api)
```suggestion
- [Using the REST API](#using-the-rest-api)
```

2023-03-16 13:16 UTC, janpio commented on .github/readmes/typescript/rest-express-auth/README.md
> +This example shows how to implement a **GraphQL server with TypeScript** with the following stack:
```suggestion
This example shows how to implement a **REST API with TypeScript** with the following stack:
```

2023-03-20 22:08 UTC, gautvm commented
Hey @ruheni 👋

I've incorporated all of your requested changes. As for the protected routes, I've modified the ones that I thought required protection based on your guidance, although please feel free to suggest any alterations if you'd propose something different.

Please let me know if there's anything else you'd like me to change 🙂

2023-03-21 17:29 UTC, eternalmoon1234 commented
Do I need to update the `rest` test now that there are protected routes?

2023-03-22 07:46 UTC, ruheni commented
Hey 👋🏾 
I would recommend creating a new test and collection for it to get the tests to pass.

2023-04-01 18:17 UTC, eternalmoon1234 commented
Sounds good, I'll go ahead and write the new test in.

2023-05-16 05:18 UTC, eternalmoon1234 commented
Hey @ruheni 👋 

The tests should pass now. Mind running the checks & verifying that everything's all good? If so, I think this is ready to merge.

2024-04-20 10:06 UTC, XprabhatX commented
The logs for the failed test are no longer available. Can anyone specify what's the problem.

2024-12-20 17:34 UTC, jharrell commented
Hello!

We are reviewing our old pull requests in this repo. If we believe that the PR is stale or abandoned, we're going to close them. 

We'd still love to have your contribution! If you'd be willing to pick this PR back up, please just comment or open a new pull request and we'll hop on it 🙏

2024-12-20 17:34 UTC, closed without merging