Improve TypeScript typing
prisma/prisma-examples pull request #3667
Opened 2022-04-10 05:59 UTC by altano

This example was very helpful in getting me rolling. The one thing it was missing was good TypeScript (TS) typing. TS is enabled in the project but `strict` is set to `false` in tsconfig.json, and there is a lot of `any` types in the code. To improve this, I:

- Switched to `strict: true` in tsconfig.json
- Added @graphql-codegen packages to the project to automatically generate TS types from the GraphQL queries.
- Update `generate` package.json script to run this new codegen.
- Fix all the TS errors (e.g. implicit any types)

This should make this boilerplate much more strictly typed and generally useful.

2022-04-24 09:50 UTC, ruheni requested changes
Hi @altano 👋🏽

Thanks for the contribution. This looks good. 

Before we merge this PR, could you:
- [ ] Exclude the generated files from the example
- [ ] Update the `.gitignore` file to exclude generated files
- [ ] Update the test for this example to include the `generate` script

2022-04-24 09:50 UTC, ruheni commented on typescript/graphql-nextjs/pages/index.tsx
> +          )}
Let's conditionally render the data here. This should not be nullable because the query will always return either an empty array or an array that's populated.

2022-04-24 09:50 UTC, ruheni commented on typescript/graphql-nextjs/pages/drafts.tsx
> +          {data?.drafts?.map(
This shouldn't be nullable here. Let's use conditional rendering

2022-04-24 09:50 UTC, ruheni commented on typescript/graphql-nextjs/pages/drafts.tsx
> +type Draft = NonNullable<Drafts>[number]
The generated GraphQL types have the correct types you can use when making queries and mutations, let's use that here.

Refer to [Apollo Client 3 with GraphQL Code Generator](https://youtu.be/PYDGjTufGsk) video by Jamie Barton or the repository he created https://github.com/notrab/graphql.wtf-graphql-codegen-apollo-client on how to use the generated types in the application.

2022-04-24 09:50 UTC, ruheni commented on typescript/graphql-nextjs/pages/drafts.tsx
> +type Draft = NonNullable<Drafts>[number]
The same applies to the sections where types for queries have been manually defined - let's use the generated types.

2023-12-18 15:43 UTC, jharrell commented
Unfortunately, going to close this as abandoned. If you'd like, please open a new PR and we'll give it another look

2023-12-18 15:43 UTC, closed without merging